server:
  port: 9000
  tomcat:
    basedir: target/tomcat
    accesslog:
      enabled: true
      buffered: false
      directory: logs
      pattern: common

logging:
  level:
    account.rogers.com: INFO
    org.springframework.web: INFO
