@startuml

actor Client

box "Account API" #LightBlue
    boundary "Get Authorized Contacts List" as AuthorizedContactsList
end box

box "Microservice" #LightGreen
    boundary "Contacts Microservice" as Contacts
	database Cassandra
end box

activate AuthorizedContactsList

Client -> AuthorizedContactsList: ""GET /v1/customer/accounts/{accountId}/contacts""

AuthorizedContactsList -> AuthorizedContactsList: Check authorization

activate Contacts

AuthorizedContactsList ->> Contacts: ""GET /v1/contact/accounts/{accountId}""
note right of AuthorizedContactsList : ""apiKey"" header
Contacts ->> Cassandra: Fetch contact details
Contacts <-- Cassandra
AuthorizedContactsList <-- Contacts
note left of Contacts
[
    {
        "accountNumber": "694762329",
        "contactId": "18057648",
        "role": "Primary",
        "firstName": "GEORGE",
        "middleName": null,
        "lastName": "WENSING",
        "effectiveDate": "2019-02-03 00:00:00+0000"
    },
    {
        "accountNumber": "694762329",
        "contactId": "CO1012172333",
        "role": "General Contact",
        "firstName": "krista",
        "middleName": null,
        "lastName": "hartvich",
        "effectiveDate": "1753-01-01 00:00:00+0000"
    }
]
end note

deactivate Contacts

AuthorizedContactsList -> AuthorizedContactsList: Map response
Client <- AuthorizedContactsList
note left of AuthorizedContactsList
[
    {
        "id": "18057648",
        "name": {
            "firstName": "George",
            "lastName": "Wensing"
        },
        "role": "Account Holder",
        "effectiveDate": "2019-02-03"
    },
    {
        "id": "CO1012172333",
        "name": {
            "firstName": "Krista",
            "lastName": "Hartvich"
        },
        "role": "Authorized Contact"
    }
]
end note

deactivate AuthorizedContactsList

@enduml
