version: '3'

services:

  account-api:
    build:
      context: ../
      dockerfile: docker/account-api/Dockerfile
    ports:
      - 9001:9000
      - 8001:8000
    environment:
      - CRYPTO_ALGORITHM=${CRYPTO_ALGORITHM}
      - CRYPTO_IV=${CRYPTO_IV}
      - CRYPTO_KEY=${CRYPTO_KEY}

      - ENV_PREFIX=${ENV_PREFIX}

      - JWT_KEYSTORE_PATH=${JWT_KEYSTORE_PATH}
      - JWT_KEYSTORE_PASSWORD=${JWT_KEYSTORE_PASSWORD}
      - JWT_KEY=${JWT_KEY}

      - MICROSERVICES_API_KEY=${MICROSERVICES_API_KEY}
      - ACCOUNT_SERVICE_CONTEXT=${ACCOUNT_SERVICE_CONTEXT}
      - CONTACTS_SERVICE_CONTEXT=${CONTACTS_SERVICE_CONTEXT}
      - SUBSCRIPTIONS_SERVICE_CONTEXT=${SUBSCRIPTIONS_SERVICE_CONTEXT}
      - FRAUD_SERVICE_CONTEXT=${FRAUD_SERVICE_CONTEXT}
    volumes:
      - ./security:/opt/data/security
    container_name: account-api
    entrypoint: java -agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n -Djava.security.egd=file:/dev/./urandom -jar app.jar

networks:
  default:
    driver: bridge