:source-highlighter: highlightjs
:toc2:
:toclevels: 2
:imagesdir: ./res
:Revision: version 1.0.0

= Account API

The Account API is responsibile for retrieving account-related information.

== link:++https://mobile-team.rogers-assets.com/api-docs/Digital-API.html#tag/Account/paths/~1v1~1customer~1accounts/get++[Get Accounts List]

=== Sequence Diagram

This is a high level sequence diagram that *does not* contain all the detailed information. +
Sample responses can be found at link:../api/core/src/test/resources[`api/core/src/test/resources`].

[plantuml, Get-Accounts-List, svg]
----
include::res/Get-Accounts-List.puml[]
----

[[get-accounts-list-response-mapping]]
=== Response Mapping

[TIP]
The assumption is that the token contains all the accounts in the consolidated hierarchy

The following cases need to be considered :

[cols=".^1,.^1,.^2,.^1,.^1,.^1,.^1,.^4,.^1", options="header"]
|===
7+^| Account Microservice                                                                                                                                                              ^| `Get Accounts List` Response ^| Note
 ^s| Account Number  ^s| Account Status  ^s| Account Type                ^s| Account Subtype ^s| Line of Business    ^s| Consolidate Account Flag    ^s| Consolidated Account Number    |                               |

9+^s| Accessing one account ( Rogers or Fido )

   | `694762329`       | `OPEN`            | `Consumer`                    | `Regular`         | `WL`                  | `false`                       | `null`                        a|
[source, json]
----
[
  {
    "accountNumber": "694762329",
    "state": "Active",
    "type": "Consumer",
    "links": [ ... ]
  }
]
----
| 

9+^s| Accessing 2 different accounts ( Rogers or Fido )

   | `694762329`       | `OPEN`            | `Consumer`                    | `Regular`         | `WL`                  | `false`                       | `null`                     .2+a|
[source, json]
----
[
  {
    "accountNumber": "694762329",
    "state": "Active",
    "type": "Consumer",
    "links": [ ... ]
  },
  {
    "accountNumber": "694762330",
    "state": "Active",
    "type": "Consumer",
    "links": [ ... ]
  }
]
----
.2+|
   | `694762330`       | `OPEN`            | `Consumer`                    | `Regular`         | `WL`                  | `false`                       | `null`

9+^s| Accessing 3 consolidated accounts ( Rogers only )

   | `634139083`       | `OPEN`            | `Consumer`                    | `Regular`         | `WL`                  | `true`                        | `null`                   .3+a|
[source, json]
----
[
  {
    "accountNumber": "634139083",
    "state": "Active",
    "type": "Consumer",
    "links": [ ... ]
  }
]
----
.3+| 
   | `224537233`       | `TENTATIVE`       | `Consumer`                    | `Regular`         | `C`                   | `true`                        | `634139083`
   | `239183759109`    | `ACTIVE`          | `Resident Pays Cable (1A0)`   | `Regular`         | `C`                   | `true`                        | `634139083`

9+^s| Accessing 3 consolidated accounts ( Rogers only ) but wireless account is `Suspended`

   | `749203238`       | `SUSPENDED`       | `Consumer`                    | `Regular`         | `WL`                  | `false`                       | `null`                   .3+a|
[source, json]
----
[
  {
    "accountNumber": "634139083",
    "state": "Active", <1>
    "type": "Consumer",
    "links": [ ... ]
  }
]
----
<1> Should the `state` be `Active` ?
.3+| 
   | `221410996`       | `OPEN`            | `Consumer`                    | `Regular`         | `C`                   | `true`                        | `749203238`
   | `240757463304`    | `ACTIVE`          | `Resident Pays Cable (1A0)`   | `.`               | `C`                   | `true`                        | `749203238`

|===

[CAUTION]
====
The following cases are missing :

* business account
* consolidated cable accounts ( no wireless account )
====

[WARNING]
.Account Microservice
====
The Account Microservice returns all the accounts in the consolidated accounts hierarchy when called using one of the consolidated account numbers. +
When called using the main account number footnote:[The account that is at the root of the hierarchy, i.e. the account that is specified in `Consolidated Account Number` ], it will only return that account. +

The token contains all the account numbers in the hierarchy but doesn't specify which one is the main and which one(s) is/are consolidated. +
We therefore need to call the Account Microservice for each account number in the token and discard the duplicated information.
====

==== Hiding the consolidation hierarchy

As shown in xref:get-accounts-list-response-mapping[the table above], only the main account is exposed by this API since the customer should only interact using that account number.

All the services linked to any of the accounts in the consolidated accounts hierarchy need to be linked to this account in the xref:get-account-details[`Get Account Details`] API. +

Since 1) the url only contains the main account number & 2) the Account microservice doesn't return the other accounts in the consolidated accounts hierarchy & 3) the Subscriptions microservice doesn't return the subscriptions linked to other accounts in the consolidated accounts hierarchy, we have to fetch the consolidated accounts hierarchy again. +
This can be done by calling the Account microservice with each account in the token or by querying the `consolidated_account` table by `parent_account_number` using the account number in the URL.

[NOTE]
====
The following questions need to be answered :

* what should be the `state`, `status` and `activationDate` of the account ?
* is it at any point required to know which account number is a service linked to ?
====

[[get-account-details]]
== link:++https://mobile-team.rogers-assets.com/api-docs/Digital-API.html#tag/Account/paths/~1v1~1customer~1accounts~1{accountId}/get++[Get Account Details]

=== Sequence Diagram

This is a high level sequence diagram that *does not* contain all the detailed information. +
Sample responses can be found at link:../api/core/src/test/resources[`api/core/src/test/resources`].

[plantuml, Get-Account-Details, svg]
----
include::res/Get-Account-Details.puml[]
----

=== Caching

Since the data is already cached by the Account and Subscriptions Microservices, this API doesn't do any caching.

=== Error Handling

At the moment, it is not possible to handle exceptions properly because of the returned status code and responses. +
For example the case where the account is not found should result a `404` but it results in a `502` since the Account Microservice returns the following :

- status code : `200`
- response body : `java.util.concurrent.CompletionException: java.util.NoSuchElementException: No value present`

=== Response Mapping

* Activation Date

A call is issued to the Subscriptions Microservice to retrieve all subscriptions for the account. +
The account activation date is derived from the effective date of the subscription with the earliest date.

* Subscription Status

The subscription status returned by the Subscriptions Microservice is mapped by this API to a `state` and a `status`. +

See below mapping for subscription statuses:
[%header,format=csv]
|===
include::res/subscriptionStatus.csv[]
|===

* Fraudulent Flag

A call is issued to the Fraud Microservice to retrieve account-level fraud details.  The `fraudulent` property is derived based on the values of `accountStatus` and `reasonCode`. +
The fraudulent propety is set to `true` if `accountStatus` is `CANCELLED` and `reasonCode` is `FRCH` or `TORF`.
Otherwise the `fraudulent` property is set to `false`.

== link:++https://mobile-team.rogers-assets.com/api-docs/Digital-API.html#tag/Contact/paths/~1v1~1customer~1accounts~1{accountId}~1contacts/get++[Get Authorized Contacts List]

=== Sequence Diagram

This is a high level sequence diagram that *does not* contain all the detailed information. +
Sample responses can be found at link:../api/core/src/test/resources[`api/core/src/test/resources`].

[plantuml, Get-Authorized-Contacts-List, svg]
----
include::res/Get-Authorized-Contacts-List.puml[]
----

=== Caching

Since the data is already cached by the Contacts Microservice, this API doesn't do any caching.

=== Response Mapping

* Names

The casing of the names returned by the Contacts Microservice is inconsistent so it is changed by this API to make it consistent.

* Effective Date

If the `effectiveDate` returned by the Contacts Microservice is `1753-01-01`, it is considered missing.

* Contacts List

There should always be at least one authorized contact since the account holder is added by default. +
If it's not the case, this API returns a `204`.

While testing we find this case :

- status code : `404`
- response body :

[source, json]
----
{"errors": [{"code":"CNT-BIZERROR","description":"No contact details found for the account number -7EYs8iVbNsxVCMhyOP8fOA==","data":null}]}
----

This case is also mapped to `204`
